require("globals")
require("options")
require("colorscheme")
require("icons")
require("lsp")
require("plugins")
require("utils")
vim.cmd("source ~/.config/nvim/vim/keymap.vim")
vim.cmd("source ~/.config/nvim/vim/autocmds.vim")
